# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cadastro(object):
    def setupUi(self, Cadastro):
        Cadastro.setObjectName("Cadastro")
        Cadastro.resize(640, 640)
        Cadastro.setMinimumSize(QtCore.QSize(640, 640))
        Cadastro.setMaximumSize(QtCore.QSize(640, 640))
        Cadastro.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.abas = QtWidgets.QTabWidget(Cadastro)
        self.abas.setGeometry(QtCore.QRect(30, 20, 580, 600))
        self.abas.setTabPosition(QtWidgets.QTabWidget.North)
        self.abas.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.abas.setElideMode(QtCore.Qt.ElideNone)
        self.abas.setDocumentMode(True)
        self.abas.setObjectName("abas")
        self.alunos = QtWidgets.QWidget()
        self.alunos.setStyleSheet("background-color: rgb(52, 161, 50);")
        self.alunos.setObjectName("alunos")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.alunos)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 507, 541))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.alunos_caixa_nome = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.alunos_caixa_nome.setMinimumSize(QtCore.QSize(0, 50))
        self.alunos_caixa_nome.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alunos_caixa_nome.setFont(font)
        self.alunos_caixa_nome.setStyleSheet("border-radius: 10px;\n"
                                             "background-color: rgb(217, 217, 217);")
        self.alunos_caixa_nome.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alunos_caixa_nome.setObjectName("alunos_caixa_nome")
        self.verticalLayout.addWidget(self.alunos_caixa_nome)
        self.alunos_caixa_sobrenome = QtWidgets.QLineEdit(
            self.verticalLayoutWidget)
        self.alunos_caixa_sobrenome.setMinimumSize(QtCore.QSize(0, 50))
        self.alunos_caixa_sobrenome.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alunos_caixa_sobrenome.setFont(font)
        self.alunos_caixa_sobrenome.setStyleSheet("border-radius: 10px;\n"
                                                  "background-color: rgb(217, 217, 217);")
        self.alunos_caixa_sobrenome.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alunos_caixa_sobrenome.setObjectName("alunos_caixa_sobrenome")
        self.verticalLayout.addWidget(self.alunos_caixa_sobrenome)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.alunos_caixa_nascimento = QtWidgets.QDateEdit(
            self.verticalLayoutWidget)
        self.alunos_caixa_nascimento.setMinimumSize(QtCore.QSize(240, 50))
        self.alunos_caixa_nascimento.setMaximumSize(QtCore.QSize(240, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alunos_caixa_nascimento.setFont(font)
        self.alunos_caixa_nascimento.setStyleSheet("border-radius: 10px;\n"
                                                   "background-color: rgb(217, 217, 217);\n"
                                                   "color: rgb(102, 102, 102);")
        self.alunos_caixa_nascimento.setObjectName("alunos_caixa_nascimento")
        self.horizontalLayout.addWidget(self.alunos_caixa_nascimento)
        self.horizontalSpacer = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(self.horizontalSpacer)
        self.alunos_comboBox_turmas = QtWidgets.QComboBox(
            self.verticalLayoutWidget)
        self.alunos_comboBox_turmas.setMinimumSize(QtCore.QSize(240, 50))
        self.alunos_comboBox_turmas.setMaximumSize(QtCore.QSize(240, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alunos_comboBox_turmas.setFont(font)
        self.alunos_comboBox_turmas.setStyleSheet("border-radius: 10px;\n"
                                                  "background-color: rgb(217, 217, 217);\n"
                                                  "color: rgb(102, 102, 102);")
        self.alunos_comboBox_turmas.setObjectName("alunos_comboBox_turmas")
        self.horizontalLayout.addWidget(self.alunos_comboBox_turmas)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.alunos_caixa_email = QtWidgets.QLineEdit(
            self.verticalLayoutWidget)
        self.alunos_caixa_email.setMinimumSize(QtCore.QSize(0, 50))
        self.alunos_caixa_email.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.alunos_caixa_email.setFont(font)
        self.alunos_caixa_email.setStyleSheet("border-radius: 10px;\n"
                                              "background-color: rgb(217, 217, 217);")
        self.alunos_caixa_email.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alunos_caixa_email.setObjectName("alunos_caixa_email")
        self.verticalLayout.addWidget(self.alunos_caixa_email)
        self.alunos_caixa_senha1 = QtWidgets.QLineEdit(
            self.verticalLayoutWidget)
        self.alunos_caixa_senha1.setMinimumSize(QtCore.QSize(0, 50))
        self.alunos_caixa_senha1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.alunos_caixa_senha1.setFont(font)
        self.alunos_caixa_senha1.setStyleSheet("border-radius: 10px;\n"
                                               "background-color: rgb(217, 217, 217);")
        self.alunos_caixa_senha1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.alunos_caixa_senha1.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alunos_caixa_senha1.setObjectName("alunos_caixa_senha1")
        self.verticalLayout.addWidget(self.alunos_caixa_senha1)
        self.alunos_caixa_senha2 = QtWidgets.QLineEdit(
            self.verticalLayoutWidget)
        self.alunos_caixa_senha2.setMinimumSize(QtCore.QSize(0, 50))
        self.alunos_caixa_senha2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.alunos_caixa_senha2.setFont(font)
        self.alunos_caixa_senha2.setStyleSheet("border-radius: 10px;\n"
                                               "background-color: rgb(217, 217, 217);")
        self.alunos_caixa_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.alunos_caixa_senha2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.alunos_caixa_senha2.setObjectName("alunos_caixa_senha2")
        self.verticalLayout.addWidget(self.alunos_caixa_senha2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.alunos_botao_voltar = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        self.alunos_botao_voltar.setMinimumSize(QtCore.QSize(150, 40))
        self.alunos_botao_voltar.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.alunos_botao_voltar.setFont(font)
        self.alunos_botao_voltar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alunos_botao_voltar.setStyleSheet("border-radius: 20px;\n"
                                               "background-color: rgb(227, 246, 0);")
        self.alunos_botao_voltar.setObjectName("alunos_botao_voltar")
        self.horizontalLayout_2.addWidget(self.alunos_botao_voltar)
        self.alunos_botao_cadastrar = QtWidgets.QPushButton(
            self.verticalLayoutWidget)
        self.alunos_botao_cadastrar.setMinimumSize(QtCore.QSize(150, 40))
        self.alunos_botao_cadastrar.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.alunos_botao_cadastrar.setFont(font)
        self.alunos_botao_cadastrar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.alunos_botao_cadastrar.setStyleSheet("border-radius: 20px;\n"
                                                  "background-color: rgb(11, 97, 144);")
        self.alunos_botao_cadastrar.setObjectName("alunos_botao_cadastrar")
        self.horizontalLayout_2.addWidget(self.alunos_botao_cadastrar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.abas.addTab(self.alunos, "")
        self.professores = QtWidgets.QWidget()
        self.professores.setStyleSheet("background-color: rgb(52, 161, 50);")
        self.professores.setObjectName("professores")
        self.scrollArea = QtWidgets.QScrollArea(self.professores)
        self.scrollArea.setGeometry(QtCore.QRect(31, 11, 525, 559))
        self.scrollArea.setMinimumSize(QtCore.QSize(525, 559))
        self.scrollArea.setMaximumSize(QtCore.QSize(525, 559))
        self.scrollArea.setStyleSheet("border: none;")
        self.scrollArea.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 525, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.professor_caixa_nome = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_nome.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_nome.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_caixa_nome.setFont(font)
        self.professor_caixa_nome.setStyleSheet("border-radius: 10px;\n"
                                                "background-color: rgb(217, 217, 217);")
        self.professor_caixa_nome.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.professor_caixa_nome.setObjectName("professor_caixa_nome")
        self.verticalLayout_2.addWidget(self.professor_caixa_nome)
        self.professor_caixa_sobrenome = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_sobrenome.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_sobrenome.setMaximumSize(
            QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_caixa_sobrenome.setFont(font)
        self.professor_caixa_sobrenome.setStyleSheet("border-radius: 10px;\n"
                                                     "background-color: rgb(217, 217, 217);")
        self.professor_caixa_sobrenome.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.professor_caixa_sobrenome.setObjectName(
            "professor_caixa_sobrenome")
        self.verticalLayout_2.addWidget(self.professor_caixa_sobrenome)
        self.professor_caixa_nascimento = QtWidgets.QDateEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_nascimento.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_nascimento.setMaximumSize(
            QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_caixa_nascimento.setFont(font)
        self.professor_caixa_nascimento.setStyleSheet("border-radius: 10px;\n"
                                                      "background-color: rgb(217, 217, 217);\n"
                                                      "color: rgb(102, 102, 102);")
        self.professor_caixa_nascimento.setObjectName(
            "professor_caixa_nascimento")
        self.verticalLayout_2.addWidget(self.professor_caixa_nascimento)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.professor_listView_materias = QtWidgets.QListWidget(
            self.scrollAreaWidgetContents)
        self.professor_listView_materias.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
                                                       "background-color: rgb(170, 255, 127);")
        self.professor_listView_materias.setObjectName(
            "professor_listView_materias")
        self.verticalLayout_3.addWidget(self.professor_listView_materias)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.professor_comboBox_materias = QtWidgets.QComboBox(
            self.scrollAreaWidgetContents)
        self.professor_comboBox_materias.setMinimumSize(QtCore.QSize(200, 50))
        self.professor_comboBox_materias.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_comboBox_materias.setFont(font)
        self.professor_comboBox_materias.setStyleSheet("border-radius: 10px;\n"
                                                       "background-color: rgb(217, 217, 217);\n"
                                                       "color: rgb(102, 102, 102);")
        self.professor_comboBox_materias.setEditable(False)
        self.professor_comboBox_materias.setObjectName(
            "professor_comboBox_materias")
        self.horizontalLayout_3.addWidget(self.professor_comboBox_materias)
        self.professor_botao_add_materia = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.professor_botao_add_materia.setMinimumSize(QtCore.QSize(30, 30))
        self.professor_botao_add_materia.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setUnderline(False)
        font.setKerning(True)
        self.professor_botao_add_materia.setFont(font)
        self.professor_botao_add_materia.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.professor_botao_add_materia.setStyleSheet("border-radius: 15px;\n"
                                                       "background-color: rgb(170, 255, 127);")
        self.professor_botao_add_materia.setObjectName(
            "professor_botao_add_materia")
        self.horizontalLayout_3.addWidget(self.professor_botao_add_materia)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.professor_listView_turmas = QtWidgets.QListWidget(
            self.scrollAreaWidgetContents)
        self.professor_listView_turmas.setStyleSheet("border: 1px solid rgb(0, 0, 0);\n"
                                                     "background-color: rgb(170, 255, 127);")
        self.professor_listView_turmas.setObjectName(
            "professor_listView_turmas")
        self.verticalLayout_4.addWidget(self.professor_listView_turmas)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.professor_comboBox_turmas = QtWidgets.QComboBox(
            self.scrollAreaWidgetContents)
        self.professor_comboBox_turmas.setMinimumSize(QtCore.QSize(200, 50))
        self.professor_comboBox_turmas.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_comboBox_turmas.setFont(font)
        self.professor_comboBox_turmas.setStyleSheet("border-radius: 10px;\n"
                                                     "background-color: rgb(217, 217, 217);\n"
                                                     "color: rgb(102, 102, 102);")
        self.professor_comboBox_turmas.setObjectName(
            "professor_comboBox_turmas")
        self.horizontalLayout_5.addWidget(self.professor_comboBox_turmas)
        self.professor_botao_add_turma = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.professor_botao_add_turma.setMinimumSize(QtCore.QSize(30, 30))
        self.professor_botao_add_turma.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.professor_botao_add_turma.setFont(font)
        self.professor_botao_add_turma.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.professor_botao_add_turma.setStyleSheet("border-radius: 15px;\n"
                                                     "background-color: rgb(170, 255, 127);")
        self.professor_botao_add_turma.setObjectName(
            "professor_botao_add_turma")
        self.horizontalLayout_5.addWidget(self.professor_botao_add_turma)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.professor_caixa_email = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_email.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_email.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.professor_caixa_email.setFont(font)
        self.professor_caixa_email.setStyleSheet("border-radius: 10px;\n"
                                                 "background-color: rgb(217, 217, 217);")
        self.professor_caixa_email.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.professor_caixa_email.setObjectName("professor_caixa_email")
        self.verticalLayout_2.addWidget(self.professor_caixa_email)
        self.professor_caixa_senha1 = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_senha1.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_senha1.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.professor_caixa_senha1.setFont(font)
        self.professor_caixa_senha1.setStyleSheet("border-radius: 10px;\n"
                                                  "background-color: rgb(217, 217, 217);")
        self.professor_caixa_senha1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.professor_caixa_senha1.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.professor_caixa_senha1.setObjectName("professor_caixa_senha1")
        self.verticalLayout_2.addWidget(self.professor_caixa_senha1)
        self.professor_caixa_senha2 = QtWidgets.QLineEdit(
            self.scrollAreaWidgetContents)
        self.professor_caixa_senha2.setMinimumSize(QtCore.QSize(0, 50))
        self.professor_caixa_senha2.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.professor_caixa_senha2.setFont(font)
        self.professor_caixa_senha2.setStyleSheet("border-radius: 10px;\n"
                                                  "background-color: rgb(217, 217, 217);")
        self.professor_caixa_senha2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.professor_caixa_senha2.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.professor_caixa_senha2.setObjectName("professor_caixa_senha2")
        self.verticalLayout_2.addWidget(self.professor_caixa_senha2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.professor_botao_voltar = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.professor_botao_voltar.setMinimumSize(QtCore.QSize(150, 40))
        self.professor_botao_voltar.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.professor_botao_voltar.setFont(font)
        self.professor_botao_voltar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.professor_botao_voltar.setStyleSheet("border-radius: 20px;\n"
                                                  "background-color: rgb(227, 246, 0);")
        self.professor_botao_voltar.setObjectName("professor_botao_voltar")
        self.horizontalLayout_4.addWidget(self.professor_botao_voltar)
        self.professor_botao_cadastrar = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.professor_botao_cadastrar.setMinimumSize(QtCore.QSize(150, 40))
        self.professor_botao_cadastrar.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.professor_botao_cadastrar.setFont(font)
        self.professor_botao_cadastrar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.professor_botao_cadastrar.setStyleSheet("border-radius: 20px;\n"
                                                     "background-color: rgb(11, 97, 144);")
        self.professor_botao_cadastrar.setObjectName(
            "professor_botao_cadastrar")
        self.horizontalLayout_4.addWidget(self.professor_botao_cadastrar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.abas.addTab(self.professores, "")

        self._translate = QtCore.QCoreApplication.translate
        self.retranslateUi(Cadastro)
        self.abas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Cadastro)
        self.professor_botao_add_materia.clicked.connect(
            self.botao_add_materia)
        self.professor_botao_add_turma.clicked.connect(self.botao_add_turma)

    def botao_add_materia(self):
        if self.professor_comboBox_materias.currentText() not in [self.professor_listView_materias.item(i).text() for i in range(self.professor_listView_materias.count())] and self.professor_comboBox_materias.currentText() != '':
            self.professor_listView_materias.addItem(
                self.professor_comboBox_materias.currentText())

    def botao_add_turma(self):
        if self.professor_comboBox_turmas.currentText() not in [self.professor_listView_turmas.item(i).text() for i in range(self.professor_listView_turmas.count())] and self.professor_comboBox_turmas.currentText() != '':
            self.professor_listView_turmas.addItem(
                self.professor_comboBox_turmas.currentText())

    def get_materias(self, materias):
        for materia in materias:
            self.professor_comboBox_materias.addItem(materia)
            self.professor_comboBox_materias.setItemText(
                materias.index(materia), materia)
        self.professor_comboBox_materias.setCurrentIndex(0)

    def get_turmas(self, turmas):
        for turma in turmas:
            self.professor_comboBox_turmas.addItem(turma)
            self.alunos_comboBox_turmas.addItem(turma)
            self.professor_comboBox_turmas.setItemText(
                turmas.index(turma), turma)
            self.alunos_comboBox_turmas.setItemText(turmas.index(turma), turma)
        self.alunos_comboBox_turmas.setCurrentIndex(0)
        self.professor_comboBox_turmas.setCurrentIndex(0)

    def retranslateUi(self, Cadastro):
        Cadastro.setWindowTitle(self._translate("Cadastro", "Cadastro"))
        self.alunos_caixa_nome.setPlaceholderText(
            self._translate("Cadastro", "Nome"))
        self.alunos_caixa_sobrenome.setPlaceholderText(
            self._translate("Cadastro", "Sobrenome"))
        self.alunos_caixa_nascimento.setDisplayFormat(
            self._translate("Cadastro", "yyyy-dd-MM"))
        self.alunos_caixa_email.setPlaceholderText(
            self._translate("Cadastro", "E-mail"))
        self.alunos_caixa_senha1.setPlaceholderText(
            self._translate("Cadastro", "Senha"))
        self.alunos_caixa_senha2.setPlaceholderText(
            self._translate("Cadastro", "Repetir Senha"))
        self.alunos_botao_voltar.setText(self._translate("Cadastro", "Voltar"))
        self.alunos_botao_cadastrar.setText(
            self._translate("Cadastro", "Cadastrar"))
        self.abas.setTabText(self.abas.indexOf(self.alunos),
                             self._translate("Cadastro", "Aluno"))
        self.professor_caixa_nome.setPlaceholderText(
            self._translate("Cadastro", "Nome"))
        self.professor_caixa_sobrenome.setPlaceholderText(
            self._translate("Cadastro", "Sobrenome"))
        self.professor_caixa_nascimento.setDisplayFormat(
            self._translate("Cadastro", "yyyy-dd-MM"))
        self.professor_botao_add_materia.setText(
            self._translate("Cadastro", "↑"))
        self.professor_botao_add_turma.setText(
            self._translate("Cadastro", "↑"))
        self.professor_caixa_email.setPlaceholderText(
            self._translate("Cadastro", "E-mail"))
        self.professor_caixa_senha1.setPlaceholderText(
            self._translate("Cadastro", "Senha"))
        self.professor_caixa_senha2.setPlaceholderText(
            self._translate("Cadastro", "Repetir Senha"))
        self.professor_botao_voltar.setText(
            self._translate("Cadastro", "Voltar"))
        self.professor_botao_cadastrar.setText(
            self._translate("Cadastro", "Cadastrar"))
        self.abas.setTabText(self.abas.indexOf(
            self.professores), self._translate("Cadastro", "Professor"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Cadastro = QtWidgets.QWidget()
    ui = Ui_Cadastro()
    ui.setupUi(Cadastro)
    ui.get_materias(['Matemática', 'Português', 'História', 'Geografia', 'Ciências', 'Física', 'Química',
                    'Biologia', 'Inglês', 'Espanhol', 'Filosofia', 'Sociologia', 'Artes', 'Educação Física'])
    ui.get_turmas(['1º ano', '2º ano', '3º ano', '4º ano', '5º ano', '6º ano',
                  '7º ano', '8º ano', '9º ano', '1º ano EM', '2º ano EM', '3º ano EM'])
    Cadastro.show()
    sys.exit(app.exec_())
