# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(500, 500)
        Login.setMinimumSize(QtCore.QSize(500, 500))
        Login.setMaximumSize(QtCore.QSize(500, 500))
        Login.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.background_login = QtWidgets.QGroupBox(Login)
        self.background_login.setGeometry(QtCore.QRect(25, 25, 450, 450))
        self.background_login.setMinimumSize(QtCore.QSize(450, 450))
        self.background_login.setMaximumSize(QtCore.QSize(450, 450))
        self.background_login.setStyleSheet("border-radius: 10px;\n"
                                            "background-color: rgb(7, 66, 22);")
        self.background_login.setObjectName("background_login")
        self.gridLayout = QtWidgets.QGridLayout(self.background_login)
        self.gridLayout.setObjectName("gridLayout")
        self.caixa_email = QtWidgets.QLineEdit(self.background_login)
        self.caixa_email.setMinimumSize(QtCore.QSize(350, 50))
        self.caixa_email.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.caixa_email.setFont(font)
        self.caixa_email.setStyleSheet("border-radius: 10px;\n"
                                       "background-color: rgb(170, 170, 170);")
        self.caixa_email.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.caixa_email.setObjectName("caixa_email")
        self.gridLayout.addWidget(self.caixa_email, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(
            QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.botao_login = QtWidgets.QPushButton(self.background_login)
        self.botao_login.setMinimumSize(QtCore.QSize(150, 40))
        self.botao_login.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setKerning(True)
        self.botao_login.setFont(font)
        self.botao_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_login.setStyleSheet("border-radius: 20px;\n"
                                       "background-color: rgb(11, 97, 144);")
        self.botao_login.setObjectName("botao_login")
        self.horizontalLayout_6.addWidget(self.botao_login)
        self.gridLayout.addLayout(self.horizontalLayout_6, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.caixa_senha = QtWidgets.QLineEdit(self.background_login)
        self.caixa_senha.setMinimumSize(QtCore.QSize(350, 50))
        self.caixa_senha.setMaximumSize(QtCore.QSize(350, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.caixa_senha.setFont(font)
        self.caixa_senha.setStyleSheet("border-radius: 10px;\n"
                                       "background-color: rgb(170, 170, 170);")
        self.caixa_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.caixa_senha.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.caixa_senha.setObjectName("caixa_senha")
        self.gridLayout.addWidget(self.caixa_senha, 4, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.logo_escola_2 = QtWidgets.QLabel(self.background_login)
        self.logo_escola_2.setMinimumSize(QtCore.QSize(180, 180))
        self.logo_escola_2.setMaximumSize(QtCore.QSize(180, 180))
        self.logo_escola_2.setStyleSheet("background-size: contain;")
        self.logo_escola_2.setText("")
        self.logo_escola_2.setPixmap(QtGui.QPixmap("img/logo-escola.png"))
        self.logo_escola_2.setScaledContents(True)
        self.logo_escola_2.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_escola_2.setObjectName("logo_escola_2")
        self.horizontalLayout_5.addWidget(self.logo_escola_2)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.caixa_email.setPlaceholderText(_translate("Login", "E-mail"))
        self.botao_login.setText(_translate("Login", "Logar"))
        self.caixa_senha.setPlaceholderText(_translate("Login", "Senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QWidget()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
