# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from modelos import Atividade


class Ui_TelaPrincipalAluno(object):
    def setupUi(self, TelaPrincipalAluno):
        TelaPrincipalAluno.setObjectName("TelaPrincipalAluno")
        TelaPrincipalAluno.resize(900, 580)
        TelaPrincipalAluno.setMinimumSize(QtCore.QSize(900, 580))
        TelaPrincipalAluno.setMaximumSize(QtCore.QSize(900, 580))
        TelaPrincipalAluno.setStyleSheet("background-color: rgb(30, 30, 30);")
        qtRectangle = TelaPrincipalAluno.frameGeometry()
        centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        TelaPrincipalAluno.move(qtRectangle.topLeft())
        self.pages = {}
        self.materias = {}
        self.botao_logoff = QtWidgets.QPushButton(TelaPrincipalAluno)
        self.botao_logoff.setGeometry(QtCore.QRect(10, 10, 40, 20))
        self.botao_logoff.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_logoff.setStyleSheet("border-radius: 10px;\n"
                                        "background-color: blue;")
        self.botao_logoff.setObjectName("botao_logoff")
        self.botao_sair = QtWidgets.QPushButton(TelaPrincipalAluno)
        self.botao_sair.setGeometry(QtCore.QRect(240, 10, 40, 20))
        self.botao_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_sair.setStyleSheet("border-radius: 10px;\n"
                                      "background-color: red;")
        self.botao_sair.setObjectName("botao_sair")
        self.logo_escola = QtWidgets.QLabel(TelaPrincipalAluno)
        self.logo_escola.setGeometry(QtCore.QRect(60, 30, 180, 180))
        self.logo_escola.setPixmap(QtGui.QPixmap("img/logo-escola.png"))
        self.logo_escola.setScaledContents(True)
        self.logo_escola.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_escola.setObjectName("logo_escola")
        self.lateral_scrollArea = QtWidgets.QScrollArea(TelaPrincipalAluno)
        self.lateral_scrollArea.setGeometry(QtCore.QRect(0, 210, 290, 361))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lateral_scrollArea.sizePolicy().hasHeightForWidth())
        self.lateral_scrollArea.setSizePolicy(sizePolicy)
        self.lateral_scrollArea.setMinimumSize(QtCore.QSize(290, 330))
        self.lateral_scrollArea.setStyleSheet("border: none;\n"
                                              "background-color: rgb(30, 30, 30);")
        self.lateral_scrollArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lateral_scrollArea.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAsNeeded)
        self.lateral_scrollArea.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.lateral_scrollArea.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.lateral_scrollArea.setWidgetResizable(True)
        self.lateral_scrollArea.setAlignment(
            QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.lateral_scrollArea.setObjectName("lateral_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(
            QtCore.QRect(0, -17, 283, 378))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lateral_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.conteudo = QtWidgets.QFrame(TelaPrincipalAluno)
        self.conteudo.setGeometry(QtCore.QRect(290, -10, 600, 581))
        self.conteudo.setStyleSheet("background-color: rgb(30, 30, 30);")
        self.conteudo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.conteudo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.conteudo.setObjectName("conteudo")
        self.stackedWidget = QtWidgets.QStackedWidget(self.conteudo)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 580, 580))
        self.stackedWidget.setStyleSheet("background-color: rgb(33, 33, 33);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_recepcao = QtWidgets.QWidget()
        self.page_recepcao.setObjectName("page_recepcao")
        self.ultima_pagina = "page_recepcao"
        self.stackedWidget.addWidget(self.page_recepcao)

        self._translate = QtCore.QCoreApplication.translate
        self.retranslateUi(TelaPrincipalAluno)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TelaPrincipalAluno)

    def add_pagina(self, nome, atividades, funcao_criar_pagina_atividade=None):
        self.pages[nome] = QtWidgets.QWidget()
        self.pages[nome].setObjectName(nome)
        self.rotulo_novas_atividades = QtWidgets.QLabel(self.pages[nome])
        self.rotulo_novas_atividades.setGeometry(QtCore.QRect(10, 10, 560, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.rotulo_novas_atividades.setFont(font)
        self.rotulo_novas_atividades.setStyleSheet("color: white;")
        self.rotulo_novas_atividades.setObjectName("rotulo_novas_atividades")
        self.line = QtWidgets.QFrame(self.pages[nome])
        self.line.setGeometry(QtCore.QRect(10, 50, 560, 7))
        self.line.setStyleSheet("")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.conteudo_scrollArea = QtWidgets.QScrollArea(self.pages[nome])
        self.conteudo_scrollArea.setGeometry(QtCore.QRect(10, 60, 561, 501))
        self.conteudo_scrollArea.setStyleSheet("border: none;")
        self.conteudo_scrollArea.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.conteudo_scrollArea.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.conteudo_scrollArea.setWidgetResizable(True)
        self.conteudo_scrollArea.setObjectName("conteudo_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(
            QtCore.QRect(0, 0, 544, 221))
        self.scrollAreaWidgetContents_2.setObjectName(
            "scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(
            self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.itens_atividade = {}
        for i, atividade in enumerate(atividades.values()):
            self.itens_atividade.update({atividade.titulo: ItemAtividade(self.scrollAreaWidgetContents_2)})
            # self.botoes_atividades[atividade.titulo] = QtWidgets.QPushButton(
            #     self.scrollAreaWidgetContents_2)
            # sizePolicy = QtWidgets.QSizePolicy(
            #     QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
            # sizePolicy.setHorizontalStretch(0)
            # sizePolicy.setVerticalStretch(0)
            # sizePolicy.setHeightForWidth(
            #     self.botoes_atividades[atividade.titulo].sizePolicy().hasHeightForWidth())
            # self.botoes_atividades[atividade.titulo].setSizePolicy(sizePolicy)
            # self.botoes_atividades[atividade.titulo].setMinimumSize(
            #     QtCore.QSize(120, 150))
            # self.botoes_atividades[atividade.titulo].setMaximumSize(
            #     QtCore.QSize(120, 150))
            # self.botoes_atividades[atividade.titulo].setCursor(
            #     QtGui.QCursor(QtCore.Qt.PointingHandCursor))
            # self.botoes_atividades[atividade.titulo].setLayoutDirection(
            #     QtCore.Qt.LeftToRight)
            # self.botoes_atividades[atividade.titulo].setAutoFillBackground(False)
            # self.botoes_atividades[atividade.titulo].setStyleSheet("border-radius: 10px;\n"
            #                                              "color: red;\n"
            #                                              "background-color: rgb(217, 217, 217);\n"
            #                                              "background-image: url(img/lista.png);\n"
            #                                              "background-repeat: no-repeat;\n"
            #                                              "background-position: center center;")
            # self.botoes_atividades[atividade.titulo].setObjectName(f"botao_atividade{i}")
            self.gridLayout.addWidget(
                self.itens_atividade[atividade.titulo], i // 4, i % 4, 1, 1)
            if funcao_criar_pagina_atividade:
                self.itens_atividade[atividade.titulo].botao_atividade.clicked.connect(funcao_criar_pagina_atividade(
                    atividade))
            self.itens_atividade[atividade.titulo].label_titulo_atividade.setText(
                self._translate("TelaPrincipalAluno", atividade.titulo))
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 4, 1, 1)
        self.conteudo_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.botao_fechar = QtWidgets.QPushButton(self.pages[nome])
        self.botao_fechar.setObjectName(u"botao_fechar")
        self.botao_fechar.setGeometry(QtCore.QRect(530, 10, 40, 40))
        self.botao_fechar.setFont(font)
        self.botao_fechar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_fechar.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.rotulo_novas_atividades.raise_()
        self.line.raise_()
        self.conteudo_scrollArea.raise_()
        self.botao_fechar.raise_()
        self.ultima_pagina = self.stackedWidget.currentWidget().objectName()
        self.stackedWidget.addWidget(self.pages[nome])

        def alterar_pagina():
            if self.stackedWidget.currentWidget().objectName() == nome:
                return
            elif self.stackedWidget.currentWidget().objectName() != "page_recepcao":
                self.materias[self.stackedWidget.currentWidget().objectName()].setStyleSheet(
                    'QPushButton {\n'
                        'border-radius: 10px;\n'
                        'background-color: rgb(252, 88, 20);\n'
                    '}'
                )
            self.stackedWidget.setCurrentWidget(self.pages[nome])
            self.materias[nome].setStyleSheet(
                'QPushButton {\n'
                    'border-radius: 10px;\n'
                    'background-color: rgb(255, 229, 0);\n'
                '}'
            )
            self.ultima_pagina = self.stackedWidget.currentWidget().objectName()

        def fechar_pagina():
            self.ultima_pagina = self.stackedWidget.currentWidget().objectName()
            self.stackedWidget.setCurrentWidget(self.page_recepcao)
            self.materias[nome].setStyleSheet(
                'QPushButton {\n'
                    'border-radius: 10px;\n'
                    'background-color: rgb(252, 88, 20);\n'
                '}'
            )
        self.materias[nome].clicked.connect(alterar_pagina)
        self.botao_fechar.clicked.connect(fechar_pagina)
        self.stackedWidget.setCurrentWidget(self.page_recepcao)
        self.rotulo_novas_atividades.setText(
            self._translate("TelaPrincipalAluno", "Novas Atividades"))
        self.botao_fechar.setText(QtCore.QCoreApplication.translate(
            "TelaPrincipalAluno", u"X", None))

    def add_materia(self, nome, atividades, funcao_criar_pagina_atividade=None):
        self.materias[nome] = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.materias[nome].setFont(font)
        self.materias[nome].setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.materias[nome].setStyleSheet(
                'QPushButton {\n'
                    'border-radius: 10px;\n'
                    'background-color: rgb(252, 88, 20);\n'
                '}'
        )
        self.materias[nome].setObjectName(nome)
        self.verticalLayout.addWidget(self.materias[nome])
        self.materias[nome].setText(
            self._translate("TelaPrincipalAluno", nome))
        self.add_pagina(nome, atividades, funcao_criar_pagina_atividade)

    def inserir_espacamento(self):
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

    def limpar_paginas(self):
        for pagina in self.pages:
            self.stackedWidget.removeWidget(self.pages[pagina])
            self.pages[pagina].deleteLater()
        if self.ultima_pagina != "page_recepcao":
            self.materias[self.ultima_pagina].setStyleSheet(
                'QPushButton {\n'
                    'border-radius: 10px;\n'
                    'background-color: rgb(252, 88, 20);\n'
                '}'
            )
        self.pages = {}

    def limpar_materias(self):
        for materia in self.materias:
            self.verticalLayout.removeWidget(self.materias[materia])
            self.materias[materia].deleteLater()
        self.materias = {}
        self.verticalLayout.removeItem(self.verticalLayout.itemAt(0))

    def retranslateUi(self, TelaPrincipalAluno):
        TelaPrincipalAluno.setWindowTitle(
            self._translate("TelaPrincipalAluno", "Tela Principal"))
        self.botao_logoff.setText(
            self._translate("TelaPrincipalAluno", "Logoff"))
        self.botao_sair.setText(self._translate("TelaPrincipalAluno", "Sair"))


class ItemAtividade(QtWidgets.QGroupBox):
    def __init__(self, scrollAreaWidgetContents):
        super().__init__(scrollAreaWidgetContents)
        self.setMinimumSize(QtCore.QSize(120, 190))
        self.setMaximumSize(QtCore.QSize(120, 190))
        self.setTitle("")
        self.setObjectName("atividade")
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.botao_atividade = QtWidgets.QPushButton(self)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.botao_atividade.sizePolicy().hasHeightForWidth())
        self.botao_atividade.setSizePolicy(sizePolicy)
        self.botao_atividade.setMinimumSize(QtCore.QSize(120, 150))
        self.botao_atividade.setMaximumSize(QtCore.QSize(120, 150))
        self.botao_atividade.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_atividade.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_atividade.setAutoFillBackground(False)
        self.botao_atividade.setStyleSheet("border-radius: 10px;\n"
                                             "background-color: rgb(217, 217, 217);\n"
                                             "background-image: url(img/lista.png);\n"
                                             "background-repeat: no-repeat;\n"
                                             "background-position: center center;")
        self.botao_atividade.setText("")
        self.botao_atividade.setObjectName("botao_atividade")
        self.verticalLayout.addWidget(self.botao_atividade)
        self.label_titulo_atividade = QtWidgets.QLabel(self)
        self.label_titulo_atividade.setMinimumSize(QtCore.QSize(120, 15))
        self.label_titulo_atividade.setMaximumSize(QtCore.QSize(120, 15))
        self.label_titulo_atividade.setStyleSheet(
            "background-color: rgb(253, 255, 102);")
        self.label_titulo_atividade.setAlignment(QtCore.Qt.AlignCenter)
        self.label_titulo_atividade.setObjectName("label_titulo_atividade")
        self.verticalLayout.addWidget(self.label_titulo_atividade)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TelaPrincipalAluno = QtWidgets.QWidget()
    ui = Ui_TelaPrincipalAluno()
    ui.setupUi(TelaPrincipalAluno)
    ui.add_materia("Matemática", {
        "MMC e MDC": Atividade(1, "MMC e MDC", "Matemática", 1, 1, 1, {}),
        "Função Afim": Atividade(2, "Função Afim", "Matemática", 1, 1, 1, {}),
        "Radiciação": Atividade(3, "Radiciação", "Matemática", 1, 1, 1, {}),
        "Potência": Atividade(4, "Potência", "Matemática", 1, 1, 1, {}),
        "Equações": Atividade(5, "Equações", "Matemática", 1, 1, 1, {}),
    })
    # ui.add_materia("Química")
    # ui.add_materia("História")
    # ui.add_materia("Inglês")
    # ui.add_materia("Física")
    # ui.add_materia("Geografia")
    # ui.add_materia("Inglês")
    # ui.add_materia("Física")
    # ui.add_materia("Geografia")
    # ui.add_materia("Inglês")
    # ui.add_materia("Física")
    ui.inserir_espacamento()
    TelaPrincipalAluno.show()
    sys.exit(app.exec_())
