# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_atividade.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaAtividade(object):
    def setupUi(self, Atividade, atividade):
        self.atividade = atividade
        Atividade.setObjectName("Atividade")
        Atividade.resize(900, 580)
        Atividade.setMinimumSize(QtCore.QSize(900, 580))
        Atividade.setMaximumSize(QtCore.QSize(900, 580))
        Atividade.setStyleSheet("background-color: rgb(51, 51, 51);")
        qtRectangle = Atividade.frameGeometry()
        centerPoint = QtWidgets.QDesktopWidget().availableGeometry().center()
        qtRectangle.moveCenter(centerPoint)
        Atividade.move(qtRectangle.topLeft())
        self.scrollArea = QtWidgets.QScrollArea(Atividade)
        self.scrollArea.setGeometry(QtCore.QRect(20, 20, 861, 541))
        self.scrollArea.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.scrollArea.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 843, 932))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(
            self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rotulo_titulo = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(32)
        self.rotulo_titulo.setFont(font)
        self.rotulo_titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.rotulo_titulo.setObjectName("rotulo_titulo")
        self.verticalLayout.addWidget(self.rotulo_titulo)
        self.rotulo_descricao = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rotulo_descricao.setFont(font)
        self.rotulo_descricao.setStyleSheet("text-align:justify;")
        self.rotulo_descricao.setTextFormat(QtCore.Qt.PlainText)
        self.rotulo_descricao.setScaledContents(False)
        self.rotulo_descricao.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignJustify | QtCore.Qt.AlignTop)
        self.rotulo_descricao.setWordWrap(True)
        self.rotulo_descricao.setObjectName("rotulo_descricao")
        self.verticalLayout.addWidget(self.rotulo_descricao)
        self.questoes = {}
        self.botao_voltar = QtWidgets.QPushButton(Atividade)
        self.botao_voltar.setGeometry(QtCore.QRect(0, 0, 40, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.botao_voltar.setFont(font)
        self.botao_voltar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_voltar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_voltar.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.botao_voltar.setObjectName("botao_voltar")

        self._translate = QtCore.QCoreApplication.translate
        self.retranslateUi(Atividade)
        QtCore.QMetaObject.connectSlotsByName(Atividade)

    def add_questao(self, num, enunciado, resposta, alternativas):
        self.questoes[num] = QuestaoAtividade(
            self.scrollAreaWidgetContents, num, resposta)
        self.verticalLayout.addWidget(self.questoes[num])
        self.questoes[num].num_questao.setText(
            self._translate("Atividade", str(num)))
        self.questoes[num].enunciado.setText(
            self._translate("Atividade", f'{enunciado}'))
        self.questoes[num].selecao['a'].setText(self._translate(
            "Atividade", f"A) {alternativas[0]}"))
        self.questoes[num].selecao['b'].setText(self._translate(
            "Atividade", f"B) {alternativas[1]}"))
        self.questoes[num].selecao['c'].setText(self._translate(
            "Atividade", f"C) {alternativas[2]}"))
        self.questoes[num].selecao['d'].setText(self._translate(
            "Atividade", f"D) {alternativas[3]}"))
        self.questoes[num].selecao['e'].setText(self._translate(
            "Atividade", f"E) {alternativas[4]}"))

    def add_rodape(self):
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.botao_verificar = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.botao_verificar.setMinimumSize(QtCore.QSize(0, 30))
        self.botao_verificar.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.botao_verificar.setFont(font)
        self.botao_verificar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_verificar.setStyleSheet("border: none;\n"
                                           "border-radius: 15px;\n"
                                           "background-color: rgb(0, 224, 22);")
        self.botao_verificar.setObjectName("botao_verificar")
        self.horizontalLayout_2.addWidget(self.botao_verificar)
        self.botao_publicar = QtWidgets.QPushButton(
            self.scrollAreaWidgetContents)
        self.botao_publicar.setMinimumSize(QtCore.QSize(0, 30))
        self.botao_publicar.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.botao_publicar.setFont(font)
        self.botao_publicar.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_publicar.setStyleSheet("border: none;\n"
                                          "border-radius: 15px;\n"
                                          "background-color: rgb(0, 166, 202);")
        self.botao_publicar.setObjectName("botao_publicar")
        self.horizontalLayout_2.addWidget(self.botao_publicar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.botao_verificar.setText(self._translate("Atividade", "Verificar"))
        self.botao_publicar.setText(self._translate("Atividade", "Responder"))

    def retranslateUi(self, Atividade):
        Atividade.setWindowTitle(self._translate("Atividade", "Atividade"))
        self.botao_voltar.setText(self._translate("Atividade", "←"))
        self.rotulo_titulo.setText(self._translate("Atividade", self.atividade.titulo))
        self.rotulo_descricao.setText(self._translate("Atividade", self.atividade.descricao))


class QuestaoAtividade(QtWidgets.QGroupBox):
    def __init__(self, scrollAreaWidgetContents, num, resposta):
        super().__init__(scrollAreaWidgetContents)
        self.resposta = resposta
        self.setMinimumSize(QtCore.QSize(825, 300))
        self.setMaximumSize(QtCore.QSize(825, 16777215))
        self.setStyleSheet("background-color: rgb(52, 161, 50);")
        self.setTitle("")
        self.setObjectName(f"questao_{num}")
        self.gridLayout = QtWidgets.QGridLayout(self)
        self.gridLayout.setObjectName("gridLayout")
        self.layoutWidget = QtWidgets.QWidget(self)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 120, 721, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num_questao = QtWidgets.QLabel(self)
        self.num_questao.setMinimumSize(QtCore.QSize(30, 30))
        self.num_questao.setMaximumSize(QtCore.QSize(30, 30))
        self.num_questao.setGeometry(QtCore.QRect(10, 10, 30, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.num_questao.setFont(font)
        self.num_questao.setStyleSheet("border-radius: 15px;\n"
                                       "background-color: rgb(252, 88, 20);")
        self.num_questao.setAlignment(QtCore.Qt.AlignCenter)
        self.num_questao.setObjectName("num_questao")
        self.gridLayout.addWidget(self.num_questao, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.enunciado = QtWidgets.QLabel(self)
        self.enunciado.setGeometry(QtCore.QRect(50, 10, 761, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enunciado.setFont(font)
        self.enunciado.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignJustify | QtCore.Qt.AlignTop)
        self.enunciado.setWordWrap(True)
        self.enunciado.setObjectName("enunciado")
        self.gridLayout.addWidget(self.enunciado, 1, 2, 1, 1)
        self.selecao = {}
        self.selecao['a'] = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selecao['a'].setFont(font)
        self.selecao['a'].setObjectName("A")
        self.verticalLayout.addWidget(self.selecao['a'])
        self.selecao['b'] = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selecao['b'].setFont(font)
        self.selecao['b'].setObjectName("B")
        self.verticalLayout.addWidget(self.selecao['b'])
        self.selecao['c'] = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selecao['c'].setFont(font)
        self.selecao['c'].setObjectName("C")
        self.verticalLayout.addWidget(self.selecao['c'])
        self.selecao['d'] = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selecao['d'].setFont(font)
        self.selecao['d'].setObjectName("D")
        self.verticalLayout.addWidget(self.selecao['d'])
        self.selecao['e'] = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selecao['e'].setFont(font)
        self.selecao['e'].setObjectName("E")
        self.verticalLayout.addWidget(self.selecao['e'])
        self.verticalLayout.setStretch(0, 10)
        self.gridLayout.addWidget(self.layoutWidget, 2, 2, 1, 1)

    def alternativa_selecionada(self):
        for letra, alternativa in self.selecao.items():
            if alternativa.isChecked():
                return letra


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Atividade = QtWidgets.QWidget()
    ui = Ui_TelaAtividade()
    ui.setupUi(Atividade, "historia")
    ui.add_questao(1, "(Enem - 2016) Uma liga metálica sai do forno a uma temperatura de 3 000 ºC e diminui 1% de sua temperatura a cada 30 min. Use 0,477 como aproximação para log10(3) e 1,041 como aproximação para log10(11). O tempo decorrido, em hora, até que a liga atinja 30 °C é mais próximo de:",
                   ["22", "50", "100", "200", "400"])
    ui.add_questao(2, "(UFRGS - 2016) Se 10x = 20y, atribuindo 0,3 para log 2, então o valor de x/y é",
                   ["0,3", "0,5", "0,7", "1", "1,3"])
    ui.add_questao(3, "(Enem - 2016) Uma liga metálica sai do forno a uma temperatura de 3 000 ºC e diminui 1% de sua temperatura a cada 30 min. Use 0,477 como aproximação para log10(3) e 1,041 como aproximação para log10(11). O tempo decorrido, em hora, até que a liga atinja 30 °C é mais próximo de:",
                   ["22", "50", "100", "200", "400ldldldldldldldldldldldldldldldldldldldld"])
    ui.add_rodape()
    Atividade.show()
    sys.exit(app.exec_())
